### ISSUE TITLE
Conditional Request Handling

### ISSUE THREAD

**Issue by allenhwkim** [allenhwkim/http-request-middleware#2]
Assuming that `/foo` is requested, and response is `/api/foo.json`
However, developers wants to send different response based on the reqest condition. e.g. 
* request method: GET, POST, PUT, DELETE
* request parameter and value
* request payload

Solution: 
1. Handle conditional configuration. e.g.
```
{
  "/api/foo": {
    "responses": [ {
      "name": "case 1", 
      "condition": "method === POST", 
      "url": "api-responses/foo.json",
      "active": true
    },{
      "name": "case 2",
      "condition": "method === GET && search.foo == '1'",
      "url": "api-responses/foo-a.json",
      "active": true
    }
  ]}
  ...
}
```
2. Change grouping of admin UI display

 *  from: pattern
 *  to: pattern and condition

**Comment by viscomd** [comment]
Can this be closed now?
